site_name: Cultura Clásica
site_url: https://moronbandin.github.io/cucla/

theme:
  name: material
  language: gl

  # CORES (modo claro/escuro con conmutador)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green        # ex.: indigo, teal, blue, deep purple... ou HEX vía extra CSS
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Mudar a modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Mudar a modo claro

  # FONTE (texto e código)
  font:
    text: "Inter"          # ou "Roboto", "Source Sans 3", "Noto Sans"...
    code: "JetBrains Mono" # ou "Fira Code", "Roboto Mono"...

  # LOGO e FAVICON (pon os ficheiros en docs/assets/)
  logo: assets/logo.svg
  favicon: assets/favicon.png



  # MÁIS FUNCIONALIDADES dispoñibles
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.sections        # ← mostra as seccións na sidebar
    - navigation.indexes         # ← usa index.md como portada da carpeta
    - navigation.tracking        # ← resalta elemento activo
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - header.autohide
plugins:
  - search
  - tags

# Extensións Markdown
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.extra
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# CSS/JS extra para personalizar a tope
extra_css:
  - styles/extra.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css  
extra_javascript:
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/medium-zoom@1.1.0/dist/medium-zoom.min.js
  - js/zoom-init.js

# Info do repo (para botón “Editar esta páxina” e ligazóns a GitHub)
repo_url: https://github.com/moronbandin/cucla
repo_name: moronbandin/cucla
edit_uri: edit/main/docs/

# Avisos, analíticas, social, etc. (opcional)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moronbandin
      name: GitHub
  # announcement: "🗞️ Aviso: entrega do proxecto o venres."

nav:
  - Inicio: index.md
  - 1AV:
      - "UD1 · Xeografía clásica":
          - "Portada": UNIDADES/1AV/1/index.md
          - "Teoría": UNIDADES/1AV/1/teoria/index.md
      - "UD2 · Historia xeral (Grecia→Roma)":
          - "Portada": UNIDADES/1AV/2/index.md
      - "UD3 · Mitoloxía e pervivencia":
          - "Portada": UNIDADES/1AV/3/index.md
      - "UD4 · Relixión grega e romana":
          - "Portada": UNIDADES/1AV/4/index.md
  - 2AV:
      - "UD5 · Arte grega":
          - "Portada": UNIDADES/2AV/5/index.md
      - "UD6 · Arte romana e romanización":
          - "Portada": UNIDADES/2AV/6/index.md
      - "UD7 · Sociedade e vida cotiá":
          - "Portada": UNIDADES/2AV/7/index.md
      - "UD8 · Política e dereito":
          - "Portada": UNIDADES/2AV/8/index.md
  - 3AV:
      - "UD9 · Linguas e alfabetos":
          - "Portada": UNIDADES/3AV/9/index.md
      - "UD10 · Léxico: latinismos e helenismos":
          - "Portada": UNIDADES/3AV/10/index.md
      - "UD11 · Espectáculos e deporte":
          - "Portada": UNIDADES/3AV/11/index.md
      - "UD12 · Pervivencia e recepción crítica":
          - "Portada": UNIDADES/3AV/12/index.md
